### ISSUE TITLE
Release_Management.wiki cleanup

### ISSUE THREAD

**Issue by pascalchevrel** [pascalchevrel/rmdocs#1]
Source Page: 
https://wiki.mozilla.org/index.php?title=Release_Management&oldid=1177887

# TODO
TOC:
- [ ] update logo

CONTRIBUTE SECTION:
- [ ] Google Play scripts to upload APK and manage translations
-> links are 404

TEAM INFO:

COMMUNICATION CHANNELS:
- [ ] add @FirefoxNightly twitter
- [ ] add blog

MEETINGS:
- [ ] add UTC times like on https://wiki.mozilla.org/Firefox/Channels/Meetings

CALENDAR UPDATING
- [ ] check that the steps still work with the new google calendar UX

TEAM RESOURCES
- [ ] remove all aurora mentions in text
- [ ]  remove "Aurora Landing Process What we do during the Aurora cycle" and put an Obsolete warning on the top of the linked page
- [ ] remove "Aurora channel Blockers and Regressions"
- [ ] "Hot fix process documentation"
  -> outdated process? System add-on instead?

DASHBOARD LINKS
- [ ] remove "Aurora, Beta Uplifts Dashboard"
- [ ] remove "Aurora channel Blockers and Regressions"

TOOLS

--
### QUESTIONS
- [ ]  remove "Our Release Survey ?" https://wiki.mozilla.org/User:Akeybl/Release_Dash
- [ ] Chinese repack is listed with a page that doesn't exist
- [ ] Shouldn't product-details be listed as a tool?
- [ ] "Aurora, Beta Uplifts Dashboard" -> 404, remove ?
- [ ] Release sign-off meeting
-> Does it still happen? The links are dead, last meeting notes are for Firefox 27 
https://wiki.mozilla.org/Releases/Firefox_27/Final_Signoffs
- [ ] Release_Management/Quarterly_Goals for the relman team
-> last goals listed are 2015
- [ ]  remove all '"B2G pages" section?
