### ISSUE TITLE
Release_Management»Release_Process.wiki cleanup

### ISSUE THREAD

**Issue by pascalchevrel** [pascalchevrel/rmdocs#2]
Spource page 
https://wiki.mozilla.org/index.php?title=Release_Management/Release_Process&oldid=1187576

# TODO

- [ ] Remove aurora description link and all aurora mentions
- [ ] Update Main repositories graphics to remove the Aurora branch
- [ ] Reword text everywhere to say "Firefox for Desktop" (official name) instead of "Desktop Firefox"
- [ ] Remove hardcoded en-US in download links
- [ ] Replace Aurora download link by Dev Edition download link
- [ ] Remove FTP download links
- [ ] Add Firefox Nightly download link on Google Play
- [ ] Update Nightly builds frequency
- [ ] Remove Rapid Release graphics
- [ ] Remove B2G IRC channel
- [ ] Add Nightly release notes
