### ISSUE TITLE
Release_Management--Team_members update

### ISSUE THREAD

**Issue by pascalchevrel** [pascalchevrel/rmdocs#4]
Source: https://wiki.mozilla.org/index.php?title=Release_Management/Team_members&oldid=1167777

# TODO
* [ ] Add RyanVM to the team
* [ ] Put Team blogs before Alumnis
* [ ] Remove Alumni blogs
* [ ] Add the Team blog and twitter account
* [ ] Add missing blogs 
* [ ] Put a link back to "how to contact us" on the main page

# QUESTIONS
* [ ] Add Philipp to the team listed as volunteer ?
* [ ] List Bastien and Kohei?
* [ ] Sylvestre: Update title?
* [ ] Ritu: Update title?
* [ ] Add that it depends on the Product Integrity department?
* [ ] Replace all the "Desktop & Mobile RM" by "Firefox RM"?
* [ ] Add timezone next to member?
